using System.Collections.Generic;
using System.Linq;
using Common.Dtos;
using Server.Utilities;

namespace Server.Game {
    public class CardGenerator {
        private readonly IList<QuestionCard> questionCards = new List<QuestionCard>() {
            new QuestionCard("Why can't I sleep at night?", 1),
            new QuestionCard("I got 99 problems but _ ain't one.", 1),
            new QuestionCard("What's a girl's best friend?", 1),
            new QuestionCard("What's that smell?", 1),
            new QuestionCard("This is the way the world ends\nThis is the way the world ends\nNot with a bang but with _.", 1),
            new QuestionCard("What is Batman's guilty pleasure?", 1),
            new QuestionCard("TSA guidelines now prohibit _ on airplanes.", 1),
            new QuestionCard("What ended my last relationship?", 1),
            new QuestionCard("MTV's new reality show features eight washed-up celebrities living with _.", 1),
            new QuestionCard("I drink to forget _.", 1),
            new QuestionCard("I'm sorry, Professor, but I couldn't complete my homework because of _.", 1),
            new QuestionCard("Alternative medicine is now embracing the curative powers of _.", 1),
            new QuestionCard("What's that sound?", 1),
            new QuestionCard("What's the next Happy Meal toy?", 1),
            new QuestionCard("It's a pity that kids these days are all getting involved with _.", 1),
            new QuestionCard("In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.", 1),
            new QuestionCard("_. That's how I want to die.", 1),
            new QuestionCard("What does Dick Cheney prefer?", 1),
            new QuestionCard("What's the most emo?", 1),
            new QuestionCard("Instead of coal, Santa now gives the bad children _.", 1),
            new QuestionCard("Next from J.K. Rowling: Harry Potter and the Chamber of _.", 1),
            new QuestionCard("A romantic, candlelit dinner would be incomplete without _.", 1),
            new QuestionCard("White people like _.", 1),
            new QuestionCard("_. Betcha can't have just one!", 1),
            new QuestionCard("War!\nWhat is it good for?", 1),
            new QuestionCard("BILLY MAYS HERE FOR _.", 1),
            new QuestionCard("_. High five, bro.", 1),
            new QuestionCard("During sex, I like to think about _.", 1),
            new QuestionCard("What did I bring back from Mexico?", 1),
            new QuestionCard("What are my parents hiding from me?", 1),
            new QuestionCard("What will always get you laid?", 1),
            new QuestionCard("What would grandma find disturbing, yet oddly charming?", 1),
            new QuestionCard("What did the U.S. airdrop to the children of Afghanistan?", 1),
            new QuestionCard("What helps Obama unwind?", 1),
            new QuestionCard("What's there a ton of in heaven?", 1),
            new QuestionCard("Major League Baseball has banned _ for giving players an unfair advantage.", 1),
            new QuestionCard("When I am a billionaire, I shall erect a 50-foot statue to commemorate _.", 1),
            new QuestionCard("What's the new fad diet?", 1),
            new QuestionCard("When I am the President of the United States, I will create the Department of _.", 1),
            new QuestionCard("_. It's a trap!", 1),
            new QuestionCard("How am I maintaining my relationship status?", 1),
            new QuestionCard("What will I bring back in time to convince people that I am a powerful wizard?", 1),
            new QuestionCard("While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.", 1),
            new QuestionCard("Coming to Broadway this season, _: The Musical.", 1),
            new QuestionCard("What's my secret power?", 1),
            new QuestionCard("What gives me uncontrollable gas?", 1),
            new QuestionCard("But before I kill you, Mr. Bond, I must show you _.", 1),
            new QuestionCard("What never fails to liven up the party?", 1),
            new QuestionCard("What am I giving up for Lent?", 1),
            new QuestionCard("What do old people smell like? ", 1),
            new QuestionCard("The class field trip was completely ruined by _.", 1),
            new QuestionCard("When Pharaoh remained unmoved, Moses called down a plague of _.", 1),
            new QuestionCard("I do not know with which weapons World War III will be fought, but World War IV will be fought with _.", 1),
            new QuestionCard("What's Teach for America using to inspire inner city students to succeed?", 1),
            new QuestionCard("In Michael Jackson's final moments, he thought about _.", 1),
            new QuestionCard("Why do I hurt all over?", 1),
            new QuestionCard("Studies show that lab rats navigate mazes 50% faster after being exposed to _.", 1),
            new QuestionCard("Why am I sticky?", 1),
            new QuestionCard("What's my anti-drug?", 1),
            new QuestionCard("And the Academy Award for _ goes to _.", 2),
            new QuestionCard("For my next trick, I will pull _ out of _.", 2),
            new QuestionCard("_: Good to the last drop.", 1),
            new QuestionCard("What did Vin Diesel eat for dinner?", 1),
            new QuestionCard("_: kid-tested, mother-approved.", 1),
            new QuestionCard("What gets better with age?", 1),
            new QuestionCard("I never truly understood _ until I encountered _.", 2),
            new QuestionCard("Rumor has it that Vladimir Putin's favorite delicacy is _ stuffed with _.", 2),
            new QuestionCard("Lifetime presents _, the story of _.", 2),
            new QuestionCard("Make a haiku.", 3),
            new QuestionCard("In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along.", 2),
            new QuestionCard("_ is a slippery slope that leads to _.", 2),
            new QuestionCard("In a world ravaged by _, our only solace is _.", 2),
            new QuestionCard("That's right, I killed _. How, you ask? _.", 2),
            new QuestionCard("When I was tripping on acid, _ turned into _.", 2),
            new QuestionCard("_ + _ = _.", 3),
            new QuestionCard("What's the next superhero/sidekick duo?", 2),
            new QuestionCard("Dear Abby,\nI'm having some trouble with _ and would like your advice.", 1),
            new QuestionCard("After the earthquake, Sean Penn brought _ to the people of Haiti.", 1),
            new QuestionCard("In L.A. County Jail, word is you can trade 200 cigarettes for _.", 1),
            new QuestionCard("Maybe she's born with it. Maybe it's _.", 1),
            new QuestionCard("Life for American Indians was forever changed when the White Man introduced them to _.", 1),
            new QuestionCard("Next on ESPN2, the World Series of _.", 1),
            new QuestionCard("Step 1: _. Step 2: _. Step 3: Profit.", 2),
            new QuestionCard("Here is the church\nHere is the steeple\nOpen the doors\nAnd there is _.", 1),
            new QuestionCard("How did I lose my virginity?", 1),
            new QuestionCard("In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?", 1),
            new QuestionCard("What don't you want to find in your Kung Pao chicken?", 1),
            new QuestionCard("The Smithsonian Museum of Natural History has just opened an exhibit on _.", 1),
            new QuestionCard("Daddy, why is Mommy crying?", 1),
        };

        private readonly IList<AnswerCard> answerCards = new List<AnswerCard>() {
            new AnswerCard("Coat hanger abortions."),
            new AnswerCard("Man meat."),
            new AnswerCard("Autocannibalism."),
            new AnswerCard("Vigorous jazz hands."),
            new AnswerCard("Flightless birds."),
            new AnswerCard("Pictures of boobs."),
            new AnswerCard("Doing the right thing."),
            new AnswerCard("The violation of our most basic human rights."),
            new AnswerCard("Viagra."),
            new AnswerCard("Self-loathing."),
            new AnswerCard("Spectacular abs."),
            new AnswerCard("A balanced breakfast."),
            new AnswerCard("Roofies."),
            new AnswerCard("Concealing a boner."),
            new AnswerCard("Amputees."),
            new AnswerCard("The Big Bang."),
            new AnswerCard("Former President George W. Bush."),
            new AnswerCard("The Rev. Dr. Martin Luther King, Jr."),
            new AnswerCard("Smegma."),
            new AnswerCard("Being marginalized."),
            new AnswerCard("Cuddling."),
            new AnswerCard("Laying an egg."),
            new AnswerCard("The Pope."),
            new AnswerCard("Aaron Burr."),
            new AnswerCard("Genital piercings."),
            new AnswerCard("Fingering."),
            new AnswerCard("A bleached asshole."),
            new AnswerCard("Horse meat."),
            new AnswerCard("Fear itself."),
            new AnswerCard("Science."),
            new AnswerCard("Elderly Japanese men."),
            new AnswerCard("Stranger danger."),
            new AnswerCard("The terrorists."),
            new AnswerCard("Praying the gay away."),
            new AnswerCard("Same-sex ice dancing."),
            new AnswerCard("Ethnic cleansing."),
            new AnswerCard("Cheating in the Special Olympics."),
            new AnswerCard("German dungeon porn."),
            new AnswerCard("Bingeing and purging."),
            new AnswerCard("Making a pouty face."),
            new AnswerCard("William Shatner."),
            new AnswerCard("Heteronormativity."),
            new AnswerCard("Nickelback."),
            new AnswerCard("Tom Cruise."),
            new AnswerCard("The profoundly handicapped."),
            new AnswerCard("The placenta."),
            new AnswerCard("Chainsaws for hands."),
            new AnswerCard("Arnold Schwarzenegger."),
            new AnswerCard("An icepick lobotomy."),
            new AnswerCard("Goblins."),
            new AnswerCard("Object permanence."),
            new AnswerCard("Dying."),
            new AnswerCard("Foreskin."),
            new AnswerCard("A falcon with a cap on its head."),
            new AnswerCard("Hormone injections."),
            new AnswerCard("Dying of dysentery."),
            new AnswerCard("Sexy pillow fights."),
            new AnswerCard("The invisible hand."),
            new AnswerCard("A really cool hat."),
            new AnswerCard("Sean Penn."),
            new AnswerCard("Heartwarming orphans."),
            new AnswerCard("The clitoris."),
            new AnswerCard("The Three-Fifths compromise."),
            new AnswerCard("A sad handjob."),
            new AnswerCard("Men."),
            new AnswerCard("Historically black colleges."),
            new AnswerCard("A micropenis."),
            new AnswerCard("Raptor attacks."),
            new AnswerCard("Agriculture."),
            new AnswerCard("Vikings."),
            new AnswerCard("Pretending to care."),
            new AnswerCard("The Underground Railroad."),
            new AnswerCard("My humps."),
            new AnswerCard("Being a dick to children."),
            new AnswerCard("Geese."),
            new AnswerCard("Bling."),
            new AnswerCard("Sniffing glue."),
            new AnswerCard("The South."),
            new AnswerCard("An Oedipus complex."),
            new AnswerCard("Eating all of the cookies before the AIDS bake-sale."),
            new AnswerCard("Sexting."),
            new AnswerCard("YOU MUST CONSTRUCT ADDITIONAL PYLONS."),
            new AnswerCard("Mutually-assured destruction."),
            new AnswerCard("Sunshine and rainbows."),
            new AnswerCard("Count Chocula."),
            new AnswerCard("Sharing needles."),
            new AnswerCard("Being rich."),
            new AnswerCard("Skeletor."),
            new AnswerCard("A sausage festival."),
            new AnswerCard("Michael Jackson."),
            new AnswerCard("Emotions."),
            new AnswerCard("Farting and walking away."),
            new AnswerCard("The Chinese gymnastics team."),
            new AnswerCard("Necrophilia."),
            new AnswerCard("Spontaneous human combustion."),
            new AnswerCard("Yeast."),
            new AnswerCard("Leaving an awkward voicemail."),
            new AnswerCard("Dick Cheney."),
            new AnswerCard("White people."),
            new AnswerCard("Penis envy."),
            new AnswerCard("Teaching a robot to love."),
            new AnswerCard("Sperm whales."),
            new AnswerCard("Scrubbing under the folds."),
            new AnswerCard("Panda sex."),
            new AnswerCard("Whipping it out."),
            new AnswerCard("Catapults."),
            new AnswerCard("Masturbation."),
            new AnswerCard("Natural selection."),
            new AnswerCard("Opposable thumbs."),
            new AnswerCard("A sassy black woman."),
            new AnswerCard("AIDS."),
            new AnswerCard("The KKK."),
            new AnswerCard("Figgy pudding."),
            new AnswerCard("Seppuku."),
            new AnswerCard("Gandhi."),
            new AnswerCard("Preteens."),
            new AnswerCard("Toni Morrison's vagina."),
            new AnswerCard("Five-Dollar Footlongs."),
            new AnswerCard("Land mines."),
            new AnswerCard("A sea of troubles."),
            new AnswerCard("A zesty breakfast burrito."),
            new AnswerCard("Christopher Walken."),
            new AnswerCard("Friction."),
            new AnswerCard("Balls."),
            new AnswerCard("Dental dams."),
            new AnswerCard("A can of whoop-ass."),
            new AnswerCard("A tiny horse."),
            new AnswerCard("Waiting 'til marriage."),
            new AnswerCard("Authentic Mexican cuisine."),
            new AnswerCard("Genghis Khan."),
            new AnswerCard("Old-people smell."),
            new AnswerCard("Feeding Rosie O'Donnell."),
            new AnswerCard("Pixelated bukkake."),
            new AnswerCard("Friends with benefits."),
            new AnswerCard("The token minority."),
            new AnswerCard("The Tempur-Pedic Swedish Sleep System."),
            new AnswerCard("A thermonuclear detonation."),
            new AnswerCard("Take-backsies."),
            new AnswerCard("The Rapture."),
            new AnswerCard("A cooler full of organs."),
            new AnswerCard("Sweet, sweet vengeance."),
            new AnswerCard("RoboCop."),
            new AnswerCard("Keanu Reeves."),
            new AnswerCard("Drinking alone."),
            new AnswerCard("Giving 110%."),
            new AnswerCard("Flesh-eating bacteria."),
            new AnswerCard("The American Dream."),
            new AnswerCard("Taking off your shirt."),
            new AnswerCard("Me time."),
            new AnswerCard("A murder most foul."),
            new AnswerCard("The inevitable heat death of the universe."),
            new AnswerCard("The folly of man."),
            new AnswerCard("That thing that electrocutes your abs."),
            new AnswerCard("Cards Against Humanity."),
            new AnswerCard("Fiery poops."),
            new AnswerCard("Poor people."),
            new AnswerCard("Edible underpants."),
            new AnswerCard("Britney Spears at 55."),
            new AnswerCard("All-you-can-eat shrimp for $4.99."),
            new AnswerCard("Pooping back and forth. Forever."),
            new AnswerCard("Fancy Feast."),
            new AnswerCard("Jewish fraternities."),
            new AnswerCard("Being a motherfucking sorcerer."),
            new AnswerCard("Pulling out."),
            new AnswerCard("Picking up girls at the abortion clinic."),
            new AnswerCard("The homosexual agenda."),
            new AnswerCard("The Holy Bible."),
            new AnswerCard("Passive-agression."),
            new AnswerCard("Ronald Reagan."),
            new AnswerCard("Vehicular manslaughter."),
            new AnswerCard("Nipple blades."),
            new AnswerCard("Assless chaps."),
            new AnswerCard("Full frontal nudity."),
            new AnswerCard("Hulk Hogan."),
            new AnswerCard("Daddy issues."),
            new AnswerCard("The hardworking Mexican."),
            new AnswerCard("Natalie Portman."),
            new AnswerCard("Waking up half-naked in a Denny's parking lot."),
            new AnswerCard("God."),
            new AnswerCard("Sean Connery."),
            new AnswerCard("Saxophone solos."),
            new AnswerCard("Gloryholes."),
            new AnswerCard("The World of Warcraft."),
            new AnswerCard("Homeless people."),
            new AnswerCard("Scalping."),
            new AnswerCard("Darth Vader."),
            new AnswerCard("Eating the last known bison."),
            new AnswerCard("Guys who don't call."),
            new AnswerCard("Hot Pockets."),
            new AnswerCard("A time travel paradox."),
            new AnswerCard("The milk man."),
            new AnswerCard("Testicular torsion."),
            new AnswerCard("Dropping a chandelier on your enemies and riding the rope up."),
            new AnswerCard("World peace."),
            new AnswerCard("A salty surprise."),
            new AnswerCard("Poorly-timed Holocaust jokes."),
            new AnswerCard("Smallpox blankets."),
            new AnswerCard("Licking things to claim them as your own."),
            new AnswerCard("The heart of a child."),
            new AnswerCard("Robert Downey, Jr."),
            new AnswerCard("Lockjaw."),
            new AnswerCard("Eugenics."),
            new AnswerCard("A good sniff."),
            new AnswerCard("Friendly fire."),
            new AnswerCard("The taint; the grundle; the fleshy fun-bridge."),
            new AnswerCard("Wearing underwear inside-out to avoid doing laundry."),
            new AnswerCard("Hurricane Katrina."),
            new AnswerCard("Free samples."),
            new AnswerCard("Jerking off into a pool of children's tears."),
            new AnswerCard("A foul mouth."),
            new AnswerCard("The glass ceiling."),
            new AnswerCard("Republicans."),
            new AnswerCard("Explosions."),
            new AnswerCard("Michelle Obama's arms."),
            new AnswerCard("Getting really high."),
            new AnswerCard("Attitude."),
            new AnswerCard("Sarah Palin."),
            new AnswerCard("The bermensch."),
            new AnswerCard("Altar boys."),
            new AnswerCard("My soul."),
            new AnswerCard("My sex life."),
            new AnswerCard("Pedophiles."),
            new AnswerCard("72 virgins."),
            new AnswerCard("Pabst Blue Ribbon."),
            new AnswerCard("Domino's Oreo Dessert Pizza."),
            new AnswerCard("A snapping turtle biting the tip of your penis."),
            new AnswerCard("The Blood of Christ."),
            new AnswerCard("Half-assed foreplay."),
            new AnswerCard("My collection of high-tech sex toys."),
            new AnswerCard("A middle-aged man on roller skates."),
            new AnswerCard("Bitches."),
            new AnswerCard("Bill Nye the Science Guy."),
            new AnswerCard("Italians."),
            new AnswerCard("A windmill full of corpses."),
            new AnswerCard("Adderall."),
            new AnswerCard("Crippling debt."),
            new AnswerCard("A stray pube."),
            new AnswerCard("Prancing."),
            new AnswerCard("Passing a kidney stone."),
            new AnswerCard("A brain tumor."),
            new AnswerCard("Leprosy."),
            new AnswerCard("Puppies!"),
            new AnswerCard("Bees?"),
            new AnswerCard("Frolicking."),
            new AnswerCard("Repression."),
            new AnswerCard("Road head."),
            new AnswerCard("A bag of magic beans."),
            new AnswerCard("An asymmetric boob job."),
            new AnswerCard("Dead parents."),
            new AnswerCard("Public ridicule."),
            new AnswerCard("A mating display."),
            new AnswerCard("A mime having a stroke."),
            new AnswerCard("Stephen Hawking talking dirty."),
            new AnswerCard("African children."),
            new AnswerCard("Mouth herpes."),
            new AnswerCard("Overcompensation."),
            new AnswerCard("Riding off into the sunset."),
            new AnswerCard("Being on fire."),
            new AnswerCard("Tangled Slinkys."),
            new AnswerCard("Civilian casualties."),
            new AnswerCard("Auschwitz."),
            new AnswerCard("My genitals."),
            new AnswerCard("Not reciprocating oral sex."),
            new AnswerCard("Lactation."),
            new AnswerCard("Being fabulous."),
            new AnswerCard("Shaquille O'Neal's acting career."),
            new AnswerCard("My relationship status."),
            new AnswerCard("Asians who aren't good at math."),
            new AnswerCard("Alcoholism."),
            new AnswerCard("Incest."),
            new AnswerCard("Grave robbing."),
            new AnswerCard("Hope."),
            new AnswerCard("8 oz. of sweet Mexican black-tar heroin."),
            new AnswerCard("Kids with ass cancer."),
            new AnswerCard("Winking at old people."),
            new AnswerCard("The Jews."),
            new AnswerCard("Justin Bieber."),
            new AnswerCard("Doin' it in the butt."),
            new AnswerCard("A lifetime of sadness."),
            new AnswerCard("The Hamburglar."),
            new AnswerCard("Swooping."),
            new AnswerCard("Classist undertones."),
            new AnswerCard("New Age music."),
            new AnswerCard("Not giving a shit about the Third World."),
            new AnswerCard("The Kool-Aid Man."),
            new AnswerCard("A hot mess."),
            new AnswerCard("Tentacle porn."),
            new AnswerCard("Lumberjack fantasies."),
            new AnswerCard("The gays."),
            new AnswerCard("Scientology."),
            new AnswerCard("Estrogen."),
            new AnswerCard("GoGurt."),
            new AnswerCard("Judge Judy."),
            new AnswerCard("Dick fingers."),
            new AnswerCard("Racism."),
            new AnswerCard("Surprise sex!"),
            new AnswerCard("Police brutality."),
            new AnswerCard("Passable transvestites."),
            new AnswerCard("The Virginia Tech Massacre."),
            new AnswerCard("When you fart and a little bit comes out."),
            new AnswerCard("Oompa-Loompas."),
            new AnswerCard("A fetus."),
            new AnswerCard("Obesity."),
            new AnswerCard("Tasteful sideboob."),
            new AnswerCard("Hot people."),
            new AnswerCard("BATMAN!!!"),
            new AnswerCard("Black people."),
            new AnswerCard("A gassy antelope."),
            new AnswerCard("Sexual tension."),
            new AnswerCard("Third base."),
            new AnswerCard("Racially-biased SAT questions."),
            new AnswerCard("Porn stars."),
            new AnswerCard("A Super Soaker full of cat pee."),
            new AnswerCard("Muhammed (Praise Be Unto Him)."),
            new AnswerCard("Puberty."),
            new AnswerCard("A disappointing birthday party."),
            new AnswerCard("An erection that lasts longer than four hours."),
            new AnswerCard("White privilege."),
            new AnswerCard("Getting so angry that you pop a boner."),
            new AnswerCard("Wifely duties."),
            new AnswerCard("Two midgets shitting into a bucket."),
            new AnswerCard("Queefing."),
            new AnswerCard("Wiping her butt."),
            new AnswerCard("Golden showers."),
            new AnswerCard("Barack Obama."),
            new AnswerCard("Nazis."),
            new AnswerCard("A robust mongoloid."),
            new AnswerCard("An M. Night Shyamalan plot twist."),
            new AnswerCard("Getting drunk on mouthwash."),
            new AnswerCard("Lunchables."),
            new AnswerCard("Women in yogurt commercials."),
            new AnswerCard("John Wilkes Booth."),
            new AnswerCard("Powerful thighs."),
            new AnswerCard("Mr. Clean, right behind you."),
            new AnswerCard("Multiple stab wounds."),
            new AnswerCard("Cybernetic enhancements."),
            new AnswerCard("Serfdom."),
            new AnswerCard("Kanye West."),
            new AnswerCard("Women's suffrage."),
            new AnswerCard("Children on leashes."),
            new AnswerCard("Harry Potter erotica."),
            new AnswerCard("The Dance of the Sugar Plum Fairy."),
            new AnswerCard("Lance Armstrong's missing testicle."),
            new AnswerCard("Parting the Red Sea."),
            new AnswerCard("The Amish."),
            new AnswerCard("Dead babies."),
            new AnswerCard("Child beauty pageants."),
            new AnswerCard("AXE Body Spray."),
            new AnswerCard("Centaurs."),
            new AnswerCard("Copping a feel."),
            new AnswerCard("Grandma."),
            new AnswerCard("Famine."),
            new AnswerCard("The Trail of Tears."),
            new AnswerCard("The miracle of childbirth."),
            new AnswerCard("Finger painting."),
            new AnswerCard("A monkey smoking a cigar."),
            new AnswerCard("The Make-A-Wish Foundation."),
            new AnswerCard("Anal beads."),
            new AnswerCard("The Force."),
            new AnswerCard("Kamikaze pilots."),
            new AnswerCard("Dry heaving."),
            new AnswerCard("Active listening."),
            new AnswerCard("Ghosts."),
            new AnswerCard("The Hustle."),
            new AnswerCard("Peeing a little bit."),
            new AnswerCard("Another goddamn vampire movie."),
            new AnswerCard("Shapeshifters."),
            new AnswerCard("The Care Bear Stare."),
            new AnswerCard("Hot cheese."),
            new AnswerCard("A mopey zoo lion."),
            new AnswerCard("A defective condom."),
            new AnswerCard("Teenage pregnancy."),
            new AnswerCard("A Bop It."),
            new AnswerCard("Expecting a burp and vomiting on the floor."),
            new AnswerCard("Horrifying laser hair removal accidents."),
            new AnswerCard("Boogers."),
            new AnswerCard("Unfathomable stupidity."),
            new AnswerCard("Breaking out into song and dance."),
            new AnswerCard("Soup that is too hot."),
            new AnswerCard("Morgan Freeman's voice."),
            new AnswerCard("Getting naked and watching Nickelodeon."),
            new AnswerCard("MechaHitler."),
            new AnswerCard("Flying sex snakes."),
            new AnswerCard("The true meaning of Christmas."),
            new AnswerCard("My inner demons."),
            new AnswerCard("Pac-Man uncontrollably guzzling cum."),
            new AnswerCard("My vagina."),
            new AnswerCard("A homoerotic volleyball montage."),
            new AnswerCard("Actually taking candy from a baby."),
            new AnswerCard("Crystal meth."),
            new AnswerCard("Exactly what you'd expect."),
            new AnswerCard("Natural male enhancement."),
            new AnswerCard("Passive-aggressive Post-it notes."),
            new AnswerCard("Inappropriate yodeling."),
            new AnswerCard("Lady Gaga."),
            new AnswerCard("The Little Engine That Could."),
            new AnswerCard("Vigilante justice."),
            new AnswerCard("A death ray."),
            new AnswerCard("Poor life choices."),
            new AnswerCard("A gentle caress of the inner thigh."),
            new AnswerCard("Embryonic stem cells."),
            new AnswerCard("Nicolas Cage."),
            new AnswerCard("Firing a rifle into the air while balls deep in a squealing hog."),
            new AnswerCard("Switching to Geico."),
            new AnswerCard("The chronic."),
            new AnswerCard("Erectile dysfunction."),
            new AnswerCard("Home video of Oprah sobbing into a Lean Cuisine."),
            new AnswerCard("A bucket of fish heads."),
            new AnswerCard("50,000 volts straight to the nipples."),
            new AnswerCard("Being fat and stupid."),
            new AnswerCard("Hospice care."),
            new AnswerCard("A pyramid of severed heads."),
            new AnswerCard("Getting married, having a few kids, buying some stuff, retiring to Florida, and dying."),
            new AnswerCard("A subscription to Men's Fitness."),
            new AnswerCard("Crucifixion."),
            new AnswerCard("A micropig wearing a tiny raincoat and booties."),
            new AnswerCard("Some god-damn peace and quiet."),
            new AnswerCard("Used panties."),
            new AnswerCard("A tribe of warrior women."),
            new AnswerCard("The penny whistle solo from \"My Heart Will Go On.\""),
            new AnswerCard("An oversized lollipop."),
            new AnswerCard("Helplessly giggling at the mention of Hutus and Tutsis."),
            new AnswerCard("Not wearing pants."),
            new AnswerCard("Consensual sex."),
            new AnswerCard("Her Majesty, Queen Elizabeth II."),
            new AnswerCard("Funky fresh rhymes."),
            new AnswerCard("The art of seduction."),
            new AnswerCard("The Devil himself."),
            new AnswerCard("Advice from a wise, old black man."),
            new AnswerCard("Destroying the evidence."),
            new AnswerCard("The light of a billion suns."),
            new AnswerCard("Wet dreams."),
            new AnswerCard("Synergistic management solutions."),
            new AnswerCard("Growing a pair."),
            new AnswerCard("Silence."),
            new AnswerCard("An M16 assault rifle."),
            new AnswerCard("Poopy diapers."),
            new AnswerCard("A live studio audience."),
            new AnswerCard("The Great Depression."),
            new AnswerCard("A spastic nerd."),
            new AnswerCard("Rush Limbaugh's soft, shitty body."),
            new AnswerCard("Tickling Sean Hannity, even after he tells you to stop."),
            new AnswerCard("Stalin."),
            new AnswerCard("Brown people."),
            new AnswerCard("Rehab."),
            new AnswerCard("Capturing Newt Gingrich and forcing him to dance in a monkey suit."),
            new AnswerCard("Battlefield amputations."),
            new AnswerCard("An uppercut."),
            new AnswerCard("Shiny objects."),
            new AnswerCard("An ugly face."),
            new AnswerCard("Menstrual rage."),
            new AnswerCard("A bitch slap."),
            new AnswerCard("One trillion dollars."),
            new AnswerCard("Chunks of dead prostitute."),
            new AnswerCard("The entire Mormon Tabernacle Choir."),
            new AnswerCard("The female orgasm."),
            new AnswerCard("Extremely tight pants."),
            new AnswerCard("The Boy Scouts of America."),
            new AnswerCard("Stormtroopers."),
            new AnswerCard("Throwing a virgin into a volcano."),
        };

        public IList<QuestionCard> GenerateQuestions() {
            questionCards.Shuffle();

            return questionCards.ToList();
        }

        public IList<AnswerCard> GenerateAnswers() {
            answerCards.Shuffle();

            return answerCards.ToList();
        }
    }
}
